Page({
    data: {
        list: [
            {
            	type:'1',
            	typeId:'0',
            	typeName:'还款信息',
            	qas:[{
            			infoId:'1',
            			infoTxt:'我的还款状态是什么？'
            		},
            		{
            			infoId:'2',
            			infoTxt:'我的还款账号是什么？'
            		},
            		{
            			infoId:'3',
            			infoTxt:'我还款成功了吗？'
            		}
            	]
            },
            {
            	type:'2',
            	typeId:'0',
            	typeName:'银行代扣',
            	qas:[{
            			infoId:'1',
            			infoTxt:'为什么还款日扣款不成...'
            		},
            		{
            			infoId:'2',
            			infoTxt:'还款是都成功？'
            		},
            		{
            			infoId:'3',
            			infoTxt:'代扣在什么时间扣款？'
            		}
            	]
            },
            {
                type:'3',
                typeId:'0',
                typeName:'还款问题',
                qas:[{
                        infoId:'1',
                        infoTxt:'如何确保本人还款？'
                    },
                    {
                        infoId:'2',
                        infoTxt:'部分还款是什么意思？'
                    },
                    {
                        infoId:'3',
                        infoTxt:'对支持代扣的银行卡有...'
                    }
                ]
            },
            {
                type:'4',
                typeId:'0',
                typeName:'现金贷',
                qas:[{
                        infoId:'1',
                        infoTxt:'申请现金贷款时为什么？'
                    },
                    {
                        infoId:'2',
                        infoTxt:'申请现金贷款上传照片...'
                    },
                    {
                        infoId:'3',
                        infoTxt:'现金贷申请有哪些步...'
                    }
                ]
            },
            {
                type:'5',
                typeId:'0',
                typeName:'逾期问题',
                qas:[{
                        infoId:'1',
                        infoTxt:'不付款会逾期？'
                    },
                    {
                        infoId:'2',
                        infoTxt:'逾期如何收取滞纳金？'
                    },
                    {
                        infoId:'3',
                        infoTxt:'扣款失败，会产生滞纳...'
                    }
                ]
            },
            {
                type:'6',
                typeId:'0',
                typeName:'申请分期',
                qas:[{
                        infoId:'1',
                        infoTxt:'如何再次办理分期？'
                    },
                    {
                        infoId:'2',
                        infoTxt:'门店如何申请消费分期？'
                    }
                ]
            },
            {
                type:'7',
                typeId:'0',
                typeName:'微信问题',
                qas:[{
                        infoId:'1',
                        infoTxt:'微信查询还款的结果准...'
                    },
                    {
                        infoId:'2',
                        infoTxt:'还款日已过，为什么在...'
                    },
                    {
                        infoId:'2',
                        infoTxt:'为什么会提示“微信暂...'
                    }
                ]
            },
            {
                type:'8',
                typeId:'0',
                typeName:'提前还款',
                qas:[{
                        infoId:'1',
                        infoTxt:'如何取消提前还款/一次'
                    },
                    {
                        infoId:'2',
                        infoTxt:'已经申请了提前还款需...'
                    },
                    {
                        infoId:'2',
                        infoTxt:'如何申请提前还款？'
                    }
                ]
            }
        ]
    },
    onReady: function() {// Do something when page ready.

    },
    goSearch:function(){
    	wx.navigateTo({
	      url: "page/recommond/recom"
	    });
    }
});
